apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: broker
          image: 4925k/microservice-fe
          env:
            - name: BROKER_URL
              value: "http://broker.info"
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: fe
spec:
  selector:
    app: fe
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082