apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
        - name: listener
          image: 4925k/microservice-listener
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: listener
spec:
  selector:
    app: listener
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80